language: java
install: true

cache:
  directories:
  - $HOME/.m2

install:
  - mvn install -DfinalName=minionki -DskipTests=false -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: releases
  api_key:
    secure:
    415c03ddb1776d8951c58d9c9d2c725c3fd36d4d
  file: target/minionki.jar
  skip_cleanup: true
  on:
    tags: true